name: pta

services:
  pta-db:
    image: postgres:12.18-alpine
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: 
      always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
